export default {
  'data': [
    {

      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'impressions': 38,
      'cost_per_result': 38,
      'amount_spent': 38,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 39,
      'amount_spent': 39,
      'impressions': 39,
    },
    {
    
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 40,
      'amount_spent': 40,
      'impressions': 40,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 41,
      'amount_spent': 41,
      'impressions': 41,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 42,
      'amount_spent': 42,
      'impressions': 42,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 43,
      'amount_spent': 43,
      'impressions': 43,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 44,
      'amount_spent': 44,
      'impressions': 44,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 45,
      'amount_spent': 45,
      'impressions': 45,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 46,
      'amount_spent': 46,
      'impressions': 46,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 47,
      'amount_spent': 47,
      'impressions': 47,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 48,
      'amount_spent': 48,
      'impressions': 48,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 49,
      'amount_spent': 49,
      'impressions': 49,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 50,
      'amount_spent': 50,
      'impressions': 50,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 51,
      'amount_spent': 51,
      'impressions': 51,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 52,
      'amount_spent': 52,
      'impressions': 52,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 53,
      'amount_spent': 53,
      'impressions': 53,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 54,
      'amount_spent': 54,
      'impressions': 54,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 55,
      'amount_spent': 55,
      'impressions': 55,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 56,
      'amount_spent': 56,
      'impressions': 56,
    },
    {
      'ad_name':'Ad Name',
      'campaign':'Campaign Name',
      'budget':10,
      'reach':10,
      'cost_per_result': 57,
      'amount_spent': 57,
      'impressions': 57,
    },
    
  ],
  'filterableFields': ['name']
}
